Repository replicatedhq/pvmigrate, pull requests merged in 2022-04, with the labels that each got.

#77 Handle nil pod logs bufio reader
  pkg/migrate/migrate.go
Labels: type::bug, bug::normal, team::orange

#78 Update release.yaml
  .github/workflows/release.yaml
Labels: type::chore, team::blue

#79 attempt to retry getting pod logs until the pod is no longer running
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
Labels: type::bug, bug::normal, team::blue
